//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1700241_CarRental_MS2
{


    public partial class ProductDetails
    {

        /// <summary>
        /// dlProductDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataList dlProductDetails;
        protected global::System.Web.UI.WebControls.Button BtnAddToCart_ProDetail;
        protected global::System.Web.UI.WebControls.TextBox startDate;
        protected global::System.Web.UI.WebControls.TextBox endDate;
        protected global::System.Web.UI.WebControls.Calendar Calendar1;
        protected global::System.Web.UI.WebControls.Calendar Calendar2;
        
    }
}
